experiment:
  title: Single-Layer RNN
  options:
    train_n_test: 1
    visualize: 1
    show_plot: 1

  model:
    network_name: rnn
    in_dim: 4
    hidden_dims: 100
    out_dim: 1
  
  training:
    dataset_name: ctxt
    n_epochs: 100
    batch_size: 32
    total_seq_length: 1400
    seq_length: 1
    hidden_dims: 100
    n_trials: 5
    with_inputnoise: 0
    output_path: ./io/output/rnn1

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-3
    amsgrad: false

  seed: 42