experiment:
  title: Single-Layer RNN

  model:
    network_name: rnn
    in_dim: 4
    hidden_dims: 20
    out_dim: 1
  
  training:
    dataset_name: ctxt
    n_epochs: 3000 #TODO
    batch_size: 4
    seq_length: 1400
    n_trials: 5
    with_inputnoise: 1
    output_path: ./io/output/rnn1

  optimizer:
    #optimizer_name: adam
    #lr: 0.001
    #betas: [0.9, 0.999]
    #eps: 1.e-7
    #weight_decay: 1.e-6
    #amsgrad: false
    optimizer_name: lbfgs
    lr: 0.01
    max_iter: 20
    max_eval: None
    history_size: 100

  seed: 42